# Generated by Django 4.1 on 2022-09-07 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('dtnasc', models.DateField(default=datetime.date(2022, 9, 7))),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
